name: saudi_currency
description: "A Flutter package for seamlessly displaying the Saudi Riyal currency symbol within your Flutter applications."
version: 0.0.4
repository: https://github.com/Mohammad-Adel-Metwalli/saudi_currency

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - Assets/Fonts/
    - Assets/Images/
  fonts:
    - family: SaudiRiyal
      fonts:
        - asset: Assets/Fonts/saudi_riyal.ttf


  # For details regarding Fonts in packages, see
  # https://flutter.dev/to/font-from-package
